### ISSUE TITLE
不需要输人地址吗？

### ISSUE THREAD

**Issue by jhyvictory** [xdhuangsidi/qzpicker#1]
不需要输人地址吗？好像要根据实际地理经纬度，算出真太阳时，对用户输入的时间做校正的吧？

**Comment by xdhuangsidi** [comment]
动盘需要，但是这个是静盘，默认使用东八区时间，从测试数据看，就月亮的度数会有误差1-2度的误差，从开发成本考虑，就忽略来经纬度的影响。

**Comment by jhyvictory** [comment]
这个是参考Moira的源码开发的吗

**Comment by xdhuangsidi** [comment]
是的

**Comment by jhyvictory** [comment]
Moira的源码能共享一份给我吗，我也想学习一下

**Comment by xdhuangsidi** [comment]
https://linux.xidian.edu.cn/git/17788721601/moira/

**Comment by xdhuangsidi** [comment]
在eclipse允许，需要导入eclipse的一些gui库

**Comment by xdhuangsidi** [comment]
在eclipse运行，需要导入eclipse的一些gui库

**Comment by jhyvictory** [comment]
好的，我试试，非常感谢~不懂的地方再和你联系

**Comment by jhyvictory** [comment]
![图片](https://user-images.githubusercontent.com/18344919/64093594-878fb080-cd8b-11e9-92ff-dbb6d96ac0de.png)

为什么会从/home/developerTool这个文件夹去加载库文件？

**Comment by xdhuangsidi** [comment]
@jhyvictory  这份源码是我从本地开发环境上传的，我把一些库放到/home/developerTool里面，这个项目需要导入eclipse的gui库，为了方便我把这些库文件放到了该文件夹里面
